module FocusNfe
  module Recursos
    module Concerns
      module Baixavel : FocusNfe::Recursos::Base
        def download: (String identificador, formato: (String | Symbol)) -> String?
        def download_json: (String identificador) -> String?
        def download_xml: (String identificador) -> String?
        def download_pdf: (String identificador) -> String?
      end
    end
  end
end
