module FocusNfe
  module Recursos
    module Concerns
      module Baixavel : FocusNfe::Recursos::Base
        def baixar: (String identificador, formato: (String | Symbol)) -> String?
        def baixar_json: (String identificador) -> String?
        def baixar_xml: (String identificador) -> String?
        def baixar_pdf: (String identificador) -> String?
      end
    end
  end
end
