module FocusNfe
  VERSION: String

  self.@configuration: FocusNfe::Configuration?

  def self.configure: () ?{ (FocusNfe::Configuration) -> void } -> FocusNfe::Configuration
  def self.configuration: () -> FocusNfe::Configuration
  def self.client: () -> FocusNfe::Client
  def self.reset_configuration!: () -> void
end
