module FocusNfe
  module Recursos
    class Cte < FocusNfe::Recursos::Base
      include FocusNfe::Recursos::Concerns::Emitivel
      include FocusNfe::Recursos::Concerns::Consultavel
      include FocusNfe::Recursos::Concerns::Cancelavel
      include FocusNfe::Recursos::Concerns::CorrigivelCte
      include FocusNfe::Recursos::Concerns::Notificavel

      MODAIS: Hash[String, Hash[String, String]]

      private

      def esquemas_extras: (Hash[untyped, untyped] dados) -> Hash[String, String]
    end
  end
end
