module FocusNfe
  module Recursos
    class Nfce < FocusNfe::Recursos::Base
      include FocusNfe::Recursos::Concerns::Emitivel
      include FocusNfe::Recursos::Concerns::Consultavel
      include FocusNfe::Recursos::Concerns::Cancelavel
      include FocusNfe::Recursos::Concerns::Inutilizavel
      include FocusNfe::Recursos::Concerns::Enviavel
      include FocusNfe::Recursos::Concerns::Conciliavel
    end
  end
end
