module FocusNfe
  module Recursos
    class NfesRecebidas < FocusNfe::Recursos::Base
      include FocusNfe::Recursos::Concerns::Listavel
      include FocusNfe::Recursos::Concerns::Baixavel
      include FocusNfe::Recursos::Concerns::Notificavel

      def consultar: (String chave, ?completa: bool) -> untyped
      def manifestar: (String chave, tipo: String, ?justificativa: String?) -> untyped
      def emitir_evento: (String chave, tipo_evento: String, **untyped dados) -> untyped
      def cancelar_evento: (String chave) -> untyped
    end
  end
end
