module FocusNfe
  module Recursos
    class Nfgas < FocusNfe::Recursos::Base
      include FocusNfe::Recursos::Concerns::Emitivel
      include FocusNfe::Recursos::Concerns::Consultavel
      include FocusNfe::Recursos::Concerns::Cancelavel
      include FocusNfe::Recursos::Concerns::Notificavel
    end
  end
end
