module FocusNfe
  module Recursos
    class Nfse < FocusNfe::Recursos::Base
      include FocusNfe::Recursos::Concerns::Emitivel
      include FocusNfe::Recursos::Concerns::Consultavel
      include FocusNfe::Recursos::Concerns::Cancelavel
    end
  end
end
